use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::UNIX_EPOCH;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::env;
use rand::{seq::SliceRandom, Rng};
use crate::types::Pos;
use crate::merkle::WordlistTree;

/// Resolve payload and cover filenames for a given wordlist profile.
/// Returns (payload_filename, cover_filename).
pub fn wordlist_filenames(language: &str, wordlist: &str) -> (String, String) {
    match wordlist {
        "bip39" => {
            if language == "english" {
                ("payload_bip39.yaml".into(), "cover.yaml".into())
            } else {
                ("payload.yaml".into(), "cover.yaml".into())
            }
        }
        other => (format!("payload_{}.yaml", other), format!("cover_{}.yaml", other)),
    }
}

// Include auto-generated language index
#[allow(dead_code)]
mod language_index {
    include!(concat!(env!("OUT_DIR"), "/language_index.rs"));
}

/// Get embedded YAML file content by path relative to languages/ directory.
/// Returns Some(content) if file is embedded in release builds, None otherwise.
/// Path should be like "english/payload.yaml" or "latin/grammar.yaml"
/// This function is now auto-generated by build.rs
pub fn get_embedded_yaml(path: &str) -> Option<&'static str> {
    language_index::get_embedded_yaml(path)
}

/// Check if a language has embedded files (packaged with the binary)
/// In release builds, all languages with YAML files are embedded.
/// In debug builds, only English is embedded (for faster iteration).
/// This function is now auto-generated by build.rs
pub fn has_embedded_files(language: &str) -> bool {
    language_index::has_embedded_files(language)
}

#[derive(serde::Serialize, serde::Deserialize)]
struct PayloadCacheData {
    /// Sorted list of all payload words (BIP39 words) for the language.
    words: Vec<String>,
    /// Mapping from payload word -> allowed POS tags derived from payload.yaml (+ optional pos_mapping.yaml).
    pos_mapping: HashMap<String, Vec<Pos>>,
}

static PAYLOAD_CACHE_BY_LANGUAGE: OnceLock<Mutex<HashMap<String, Arc<PayloadCacheData>>>> = OnceLock::new();

fn glossia_cache_dir() -> PathBuf {
    if let Some(p) = std::env::var_os("GLOSSIA_CACHE_DIR") {
        return PathBuf::from(p);
    }
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))
        .unwrap_or_else(std::env::temp_dir);
    base.join("glossia")
}

fn file_fingerprint(path: &Path) -> Option<(u64, u64, u32)> {
    let md = std::fs::metadata(path).ok()?;
    let modified = md.modified().ok()?;
    let dur = modified.duration_since(UNIX_EPOCH).ok()?;
    Some((md.len(), dur.as_secs(), dur.subsec_nanos()))
}

fn cache_key_u64_for_language(language: &str, wordlist: &str, payload_path: Option<&Path>, pos_mapping_path: Option<&Path>) -> u64 {
    let mut hasher = DefaultHasher::new();
    language.hash(&mut hasher);
    wordlist.hash(&mut hasher);
    env!("CARGO_PKG_VERSION").hash(&mut hasher);

    let (payload_filename, _) = wordlist_filenames(language, wordlist);
    if let Some(p) = payload_path {
        p.to_string_lossy().hash(&mut hasher);
        file_fingerprint(p).hash(&mut hasher);
    } else {
        // Embedded payload. Hashing bytes is cheap vs YAML parsing and
        // keeps the cache stable across runs while auto-invalidating when the embedded data changes.
        if let Some(embedded_payload) = get_embedded_yaml(&format!("{}/{}", language, payload_filename)) {
            embedded_payload.as_bytes().hash(&mut hasher);
        }
    }

    if let Some(p) = pos_mapping_path {
        p.to_string_lossy().hash(&mut hasher);
        file_fingerprint(p).hash(&mut hasher);
    }

    hasher.finish()
}

fn payload_cache_file_path(language: &str, wordlist: &str, payload_path: Option<&Path>, pos_mapping_path: Option<&Path>) -> PathBuf {
    let key = cache_key_u64_for_language(language, wordlist, payload_path, pos_mapping_path);
    glossia_cache_dir().join(format!("payload_cache_{language}_{wordlist}_{key:016x}.bin"))
}

fn load_or_build_payload_cache(language: &str, wordlist: &str) -> Result<Arc<PayloadCacheData>, String> {
    // In-memory cache keyed on (language, wordlist).
    let cache_key = format!("{}:{}", language, wordlist);
    let cache_map = PAYLOAD_CACHE_BY_LANGUAGE.get_or_init(|| Mutex::new(HashMap::new()));
    if let Some(existing) = cache_map.lock().unwrap().get(&cache_key).cloned() {
        return Ok(existing);
    }

    let (payload_filename, _) = wordlist_filenames(language, wordlist);

    // Determine file paths (if any) for on-disk cache keying/invalidation.
    let payload_path: Option<PathBuf> = if has_embedded_files(language) {
        None
    } else {
        Some(PathBuf::from(get_wordlist_path(language, wordlist)?))
    };
    let pos_mapping_path: Option<PathBuf> = payload_path
        .as_ref()
        .and_then(|p| p.parent().map(|d| d.join("pos_mapping.yaml")))
        .filter(|p| p.exists());

    // Try on-disk cache.
    let cache_file = payload_cache_file_path(language, wordlist, payload_path.as_deref(), pos_mapping_path.as_deref());
    if let Ok(bytes) = std::fs::read(&cache_file) {
        if let Ok(data) = bincode::deserialize::<PayloadCacheData>(&bytes) {
            let arc = Arc::new(data);
            cache_map.lock().unwrap().insert(cache_key.clone(), arc.clone());
            return Ok(arc);
        }
    }

    // Build from YAML (single parse for both wordlist + POS mapping).
    let yaml_content = if let Some(embedded) = get_embedded_yaml(&format!("{}/{}", language, payload_filename)) {
        embedded.to_string()
    } else {
        let p = payload_path.as_ref().expect("payload_path must exist for non-embedded languages");
        std::fs::read_to_string(p).map_err(|e| format!("Failed to read YAML file '{}': {}", p.display(), e))?
    };

    let yaml_data: HashMap<String, HashMap<String, f64>> = serde_yaml::from_str(&yaml_content)
        .map_err(|e| format!("Failed to parse YAML: {}", e))?;

    // Load language-specific POS tag mappings (small file; only used when building cache).
    let pos_mappings = load_pos_mappings(language);

    let mut words: Vec<String> = Vec::with_capacity(yaml_data.len());
    let mut pos_mapping: HashMap<String, Vec<Pos>> = HashMap::with_capacity(yaml_data.len());

    for (word, pos_weights) in yaml_data {
        let word_lower = word.to_lowercase();
        if !word_lower.is_empty() {
            words.push(word_lower.clone());
        }

        let mut pos_tags = Vec::new();
        for (pos_str, weight) in pos_weights {
            if weight > 0.0 {
                if let Some(pos) = parse_pos_tag(&pos_str, &pos_mappings) {
                    pos_tags.push(pos);
                }
            }
        }

        if !word_lower.is_empty() && !pos_tags.is_empty() {
            pos_mapping.insert(word_lower, pos_tags);
        }
    }

    words.sort();
    words.dedup();

    let data = PayloadCacheData { words, pos_mapping };

    // Best-effort on-disk cache write (speeds up subsequent runs).
    let cache_dir = glossia_cache_dir();
    let _ = std::fs::create_dir_all(&cache_dir);
    if let Ok(bytes) = bincode::serialize(&data) {
        let _ = std::fs::write(&cache_file, bytes);
    }

    let arc = Arc::new(data);
    cache_map.lock().unwrap().insert(cache_key, arc.clone());
    Ok(arc)
}

/// Load language-specific POS tag mappings from pos_mapping.yaml
/// Returns a HashMap mapping language-specific POS tag names to Glossia POS tags
/// Returns empty HashMap if file doesn't exist (backward compatible)
fn load_pos_mappings(language: &str) -> HashMap<String, Pos> {
    // Try embedded file first (release builds)
    let yaml_content = if let Some(embedded) = get_embedded_yaml(&format!("{}/pos_mapping.yaml", language)) {
        embedded.to_string()
    } else {
        // Fall back to filesystem lookup (for debug builds or languages without embedded files)
        // Use recursive search to find pos_mapping.yaml
        if let Some(pos_mapping_path) = find_language_file(language, "pos_mapping.yaml") {
            match std::fs::read_to_string(&pos_mapping_path) {
                Ok(content) => content,
                Err(_) => return HashMap::new(), // Silently fail if can't read
            }
        } else {
            // No mapping file - return empty (backward compatible)
            return HashMap::new();
        }
    };
    
    // Parse YAML structure: { mappings: { language_pos: glossia_pos, ... } }
    #[derive(serde::Deserialize)]
    struct PosMappingFile {
        mappings: Option<HashMap<String, String>>,
    }
    
    let mapping_file: PosMappingFile = match serde_yaml::from_str(&yaml_content) {
        Ok(m) => m,
        Err(_) => return HashMap::new(), // Silently fail if can't parse
    };
    
    let mut result = HashMap::new();
    if let Some(mappings) = mapping_file.mappings {
        for (lang_pos, glossia_pos_str) in mappings {
            // Parse the Glossia POS tag string to Pos enum
            if let Some(pos) = parse_pos_tag_default(&glossia_pos_str) {
                result.insert(lang_pos, pos);
            }
        }
    }
    
    result
}

/// Build comprehensive POS mapping for all BIP39 words.
/// Returns a HashMap mapping each word to its allowed POS tags.
/// Uses YAML format (word -> POS weights) from payload.yaml.
pub fn build_pos_mapping(language: &str) -> Result<HashMap<String, Vec<Pos>>, String> {
    build_pos_mapping_for_wordlist(language, "bip39")
}

/// Build POS mapping for a specific wordlist profile.
pub fn build_pos_mapping_for_wordlist(language: &str, wordlist: &str) -> Result<HashMap<String, Vec<Pos>>, String> {
    // Use shared payload cache (parses payload.yaml once; subsequent calls are near-zero cost).
    Ok(load_or_build_payload_cache(language, wordlist)?.pos_mapping.clone())
}

/// Load POS mapping from YAML file on disk
pub fn build_pos_mapping_from_yaml(path: &str, pos_mappings: &HashMap<String, Pos>) -> Result<HashMap<String, Vec<Pos>>, String> {
    let yaml_content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read YAML file '{}': {}", path, e))?;
    build_pos_mapping_from_yaml_content(&yaml_content, pos_mappings)
}

/// Build POS mapping from YAML format.
/// YAML structure: { word: { POS: weight, ... }, ... }
/// Weights are normalized and POS tags are extracted.
pub fn build_pos_mapping_from_yaml_content(yaml_content: &str, pos_mappings: &HashMap<String, Pos>) -> Result<HashMap<String, Vec<Pos>>, String> {
    // Parse YAML as HashMap<String, HashMap<String, f64>>
    // Outer key = word, inner key = POS tag, value = weight
    let yaml_data: HashMap<String, HashMap<String, f64>> = serde_yaml::from_str(yaml_content)
        .map_err(|e| format!("Failed to parse YAML: {}", e))?;
    
    let mut mapping = HashMap::new();
    
    for (word, pos_weights) in yaml_data {
        let word_lower = word.to_lowercase();
        let mut pos_tags = Vec::new();
        
        // Extract POS tags (weights are normalized later if needed)
        // For now, we just collect all POS tags with non-zero weights
        for (pos_str, weight) in pos_weights {
            if weight > 0.0 {
                if let Some(pos) = parse_pos_tag(&pos_str, pos_mappings) {
                    pos_tags.push(pos);
                }
            }
        }
        
        // Only add words with valid POS tags
        if !word_lower.is_empty() && !pos_tags.is_empty() {
            mapping.insert(word_lower, pos_tags);
        }
    }
    
    Ok(mapping)
}

/// Parse a single POS tag string to Pos enum.
/// First checks language-specific mappings, then falls back to default POS tags.
pub fn parse_pos_tag(pos_str: &str, pos_mappings: &HashMap<String, Pos>) -> Option<Pos> {
    let pos_str_trimmed = pos_str.trim();
    
    // First check language-specific mappings
    if let Some(pos) = pos_mappings.get(pos_str_trimmed) {
        return Some(*pos);
    }
    
    // Fall back to default POS tags
    parse_pos_tag_default(pos_str_trimmed)
}

/// Parse a single POS tag string to Pos enum (default/hardcoded mappings).
pub fn parse_pos_tag_default(pos_str: &str) -> Option<Pos> {
    match pos_str {
        "Det" => Some(Pos::Det),
        "Adj" => Some(Pos::Adj),
        "N" => Some(Pos::N),
        "V" => Some(Pos::V),
        "Modal" => Some(Pos::Modal),
        "Aux" => Some(Pos::Aux),
        "Cop" => Some(Pos::Cop),
        "To" => Some(Pos::To),
        "Prep" => Some(Pos::Prep),
        "Adv" => Some(Pos::Adv),
        "Conj" => Some(Pos::Conj),
        "Dot" => Some(Pos::Dot),
        "Prefix" => Some(Pos::Prefix),
        _ => None,
    }
}

/// Get POS tags for a word from the comprehensive mapping.
/// Returns a vector of allowed POS tags.
/// Used for tagging payload (BIP39) words. Cover words use explicit POS tags from cover.yaml.
pub fn tag_word(word: &str) -> Vec<Pos> {
    // For now, use English POS mapping for tagging payload words
    // TODO: Make this language-aware if needed
    static POS_MAP: OnceLock<HashMap<String, Vec<Pos>>> = OnceLock::new();
    
    let mapping = POS_MAP.get_or_init(|| {
        // Default to English for POS tagging
        build_pos_mapping("english").unwrap_or_else(|_| HashMap::new())
    });
    
    let word_lower = word.to_lowercase();
    // Require explicit POS tags - return empty if word not found
    mapping.get(&word_lower).cloned().unwrap_or_default()
}

/// Load all payload words from the wordlist file.
/// Uses YAML format (extracts keys) from payload.yaml.
/// For languages with embedded files, uses embedded file. For other languages, tries to load from filesystem.
pub fn load_payload_words(language: &str) -> Result<Vec<String>, String> {
    load_payload_words_for_wordlist(language, "bip39")
}

/// Load payload words for a specific wordlist profile.
pub fn load_payload_words_for_wordlist(language: &str, wordlist: &str) -> Result<Vec<String>, String> {
    // Use shared payload cache (parses payload.yaml once; subsequent calls are near-zero cost).
    Ok(load_or_build_payload_cache(language, wordlist)?.words.clone())
}

/// Load payload words from embedded payload.yaml
pub fn load_payload_words_from_embedded(language: &str) -> Result<Vec<String>, String> {
    let (payload_filename, _) = wordlist_filenames(language, "bip39");
    let payload_yaml = get_embedded_yaml(&format!("{}/{}", language, payload_filename))
        .ok_or_else(|| format!("No embedded file for language: {}", language))?;
    load_payload_words_from_yaml_content(payload_yaml)
}

/// Load payload words from YAML content string (extracts keys).
pub fn load_payload_words_from_yaml_content(yaml_content: &str) -> Result<Vec<String>, String> {
    // Parse YAML as HashMap<String, HashMap<String, f64>>
    // Extract just the keys (words)
    let yaml_data: HashMap<String, HashMap<String, f64>> = serde_yaml::from_str(yaml_content)
        .map_err(|e| format!("Failed to parse YAML: {}", e))?;
    
    let mut words: Vec<String> = yaml_data.keys().cloned().collect();
    words.sort(); // Keep consistent ordering
    Ok(words)
}

/// Load payload words from YAML file (extracts keys).
pub fn load_payload_words_from_yaml(path: &str) -> Result<Vec<String>, String> {
    let yaml_content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read YAML file '{}': {}", path, e))?;
    load_payload_words_from_yaml_content(&yaml_content)
}

/// Load payload words into a WordlistTree.
/// Returns a WordlistTree with canonical ordering (sorted alphabetically for payload words).
pub fn load_payload_tree(language: &str) -> Result<WordlistTree, String> {
    let words = load_payload_words(language)?;
    Ok(WordlistTree::new(words))
}

/// Load cover words with POS tags from cover.yaml
/// Returns a HashMap mapping POS to Vec of words
/// For English, uses embedded file. For other languages, tries to load from filesystem.
pub fn load_cover_words_by_pos(wordlist_set: &HashSet<String>, language: &str) -> (HashMap<Pos, Vec<String>>, HashMap<(Pos, String), Vec<String>>) {
    load_cover_words_by_pos_for_wordlist(wordlist_set, language, "bip39")
}

/// Load cover words for a specific wordlist profile.
/// Returns (by_pos, refined_cover) where refined_cover maps (POS, refinement_tag) -> words.
pub fn load_cover_words_by_pos_for_wordlist(wordlist_set: &HashSet<String>, language: &str, wordlist: &str) -> (HashMap<Pos, Vec<String>>, HashMap<(Pos, String), Vec<String>>) {
    let (_, cover_filename) = wordlist_filenames(language, wordlist);
    // Load language-specific POS tag mappings
    let pos_mappings = load_pos_mappings(language);

    let yaml_content = if let Some(embedded) = get_embedded_yaml(&format!("{}/{}", language, cover_filename)) {
        embedded.to_string()
    } else {
        // For other languages, try to load from filesystem (with recursive search)
        let cover_yaml_path = find_language_file(language, &cover_filename)
            .unwrap_or_else(|| {
                let languages_dir = find_languages_dir()
                    .unwrap_or_else(|| "languages".to_string());
                format!("{}/{}/{}", languages_dir, language, cover_filename)
            });
        std::fs::read_to_string(&cover_yaml_path)
            .unwrap_or_else(|e| {
                eprintln!("Error: Failed to read {} from '{}': {}", cover_filename, cover_yaml_path, e);
                std::process::exit(1);
            })
    };

    // Parse with serde_yaml::Value to handle mixed types (f64 weights + string refinement tag)
    use serde_yaml::Value;
    let yaml_data: HashMap<String, Value> = serde_yaml::from_str(&yaml_content)
        .unwrap_or_else(|e| {
            eprintln!("Error: Failed to parse cover.yaml as YAML: {}", e);
            std::process::exit(1);
        });

    let mut by_pos: HashMap<Pos, Vec<String>> = HashMap::new();
    let mut refined_cover: HashMap<(Pos, String), Vec<String>> = HashMap::new();

    for (word, value) in &yaml_data {
        let word_lower = word.to_lowercase();

        // Skip if word is in wordlist set
        if wordlist_set.contains(&word_lower) {
            continue;
        }

        let mapping = match value.as_mapping() {
            Some(m) => m,
            None => continue,
        };

        // Extract refinement tag (if present)
        let refinement = mapping.get("refinement")
            .and_then(|v| v.as_str())
            .map(|s| s.to_string());

        // Extract POS tags with non-zero weights (skip "refinement" key)
        for (key, val) in mapping {
            let pos_str = match key.as_str() {
                Some(s) if s != "refinement" => s,
                _ => continue,
            };
            let weight = match val.as_f64() {
                Some(w) if w > 0.0 => w,
                _ => continue,
            };

            if weight > 0.0 {
                if let Some(pos) = parse_pos_tag(pos_str, &pos_mappings) {
                    by_pos.entry(pos).or_insert_with(Vec::new).push(word.clone());

                    // Also index by (POS, refinement) if refinement is present
                    if let Some(ref tag) = refinement {
                        refined_cover.entry((pos, tag.clone()))
                            .or_insert_with(Vec::new)
                            .push(word.clone());
                    }
                }
            }
        }
    }

    // Deduplicate and sort each category
    for words in by_pos.values_mut() {
        words.sort();
        words.dedup();
    }
    for words in refined_cover.values_mut() {
        words.sort();
        words.dedup();
    }

    (by_pos, refined_cover)
}

/// Load cover words in file order from cover.yaml.
/// Returns all cover words preserving the order from cover.yaml (never re-sorted; this IS the canonical ordering).
/// Key invariant: The file order of cover.yaml is the canonical ordering. Code must never sort this list.
pub fn load_cover_words_in_file_order(language: &str) -> Vec<String> {
    load_cover_words_in_file_order_for_wordlist(language, "bip39")
}

/// Load cover words in file order for a specific wordlist profile.
pub fn load_cover_words_in_file_order_for_wordlist(language: &str, wordlist: &str) -> Vec<String> {
    let (_, cover_filename) = wordlist_filenames(language, wordlist);
    let yaml_content = if let Some(embedded) = get_embedded_yaml(&format!("{}/{}", language, cover_filename)) {
        embedded.to_string()
    } else {
        // For other languages, try to load from filesystem (with recursive search)
        let cover_yaml_path = find_language_file(language, &cover_filename)
            .unwrap_or_else(|| {
                let languages_dir = find_languages_dir()
                    .unwrap_or_else(|| "languages".to_string());
                format!("{}/{}/{}", languages_dir, language, cover_filename)
            });
        std::fs::read_to_string(&cover_yaml_path)
            .unwrap_or_else(|e| {
                eprintln!("Error: Failed to read {} from '{}': {}", cover_filename, cover_yaml_path, e);
                std::process::exit(1);
            })
    };
    
    // Preserve file order (YAML HashMap iteration order in Rust preserves insertion order
    // for most YAML parsers, but to be safe, we'll use the order from the YAML file)
    // Actually, HashMap doesn't preserve order in Rust. We need to parse differently.
    // Let's use a different approach: parse as a sequence of key-value pairs
    
    // For now, we'll extract keys in the order they appear in the YAML string
    // This is a limitation - we need the YAML parser to preserve order
    // serde_yaml::Value preserves order when using Mapping, but HashMap doesn't
    // Let's parse as Value first, then extract keys
    
    use serde_yaml::Value;
    let value: Value = serde_yaml::from_str(&yaml_content)
        .unwrap_or_else(|e| {
            eprintln!("Error: Failed to parse cover.yaml as YAML Value: {}", e);
            std::process::exit(1);
        });
    
    let mut words = Vec::new();
    if let Value::Mapping(mapping) = value {
        // serde_yaml::Mapping preserves insertion order
        for (key, _) in mapping {
            if let Value::String(word) = key {
                words.push(word);
            }
        }
    }
    
    words
}

/// Load cover words into a WordlistTree.
/// Returns a WordlistTree preserving file order from cover.yaml (canonical ordering).
/// Key invariant: The file order of cover.yaml is the canonical ordering. Code must never sort this list.
pub fn load_cover_tree(language: &str) -> WordlistTree {
    let words = load_cover_words_in_file_order(language);
    WordlistTree::new(words)
}

/// Load POS tags for cover words from cover.yaml.
/// Returns a HashMap mapping cover word -> Vec of POS tags.
/// This allows Merkle words to be treated as PayloadToks with proper POS.
pub fn load_cover_word_pos_tags(language: &str) -> HashMap<String, Vec<Pos>> {
    load_cover_word_pos_tags_for_wordlist(language, "bip39")
}

/// Load cover word POS tags for a specific wordlist profile.
pub fn load_cover_word_pos_tags_for_wordlist(language: &str, wordlist: &str) -> HashMap<String, Vec<Pos>> {
    let (_, cover_filename) = wordlist_filenames(language, wordlist);
    // Load language-specific POS tag mappings
    let pos_mappings = load_pos_mappings(language);

    let yaml_content = if let Some(embedded) = get_embedded_yaml(&format!("{}/{}", language, cover_filename)) {
        embedded.to_string()
    } else {
        // For other languages, try to load from filesystem (with recursive search)
        let cover_yaml_path = find_language_file(language, &cover_filename)
            .unwrap_or_else(|| {
                let languages_dir = find_languages_dir()
                    .unwrap_or_else(|| "languages".to_string());
                format!("{}/{}/{}", languages_dir, language, cover_filename)
            });
        std::fs::read_to_string(&cover_yaml_path)
            .unwrap_or_else(|e| {
                eprintln!("Error: Failed to read {} from '{}': {}", cover_filename, cover_yaml_path, e);
                std::process::exit(1);
            })
    };
    
    let yaml_data: HashMap<String, HashMap<String, f64>> = serde_yaml::from_str(&yaml_content)
        .unwrap_or_else(|e| {
            eprintln!("Error: Failed to parse cover.yaml as YAML: {}", e);
            std::process::exit(1);
        });
    
    let mut result: HashMap<String, Vec<Pos>> = HashMap::new();
    
    for (word, pos_weights) in yaml_data {
        let word_lower = word.to_lowercase();
        let mut pos_tags = Vec::new();
        
        // Extract POS tags with non-zero weights
        for (pos_str, weight) in pos_weights {
            if weight > 0.0 {
                if let Some(pos) = parse_pos_tag(&pos_str, &pos_mappings) {
                    pos_tags.push(pos);
                }
            }
        }
        
        if !pos_tags.is_empty() {
            result.insert(word_lower, pos_tags);
        }
    }
    
    result
}

/// Randomly select N words from the BIP39 wordlist.
pub fn select_random_words<R: Rng>(rng: &mut R, count: usize, language: &str) -> Result<Vec<String>, String> {
    let all_words = load_payload_words(language)?;
    if all_words.is_empty() || count == 0 {
        return Ok(Vec::new());
    }

    // Sample WITH replacement so duplicates are possible (and therefore decodable).
    let mut selected = Vec::with_capacity(count);
    for _ in 0..count {
        selected.push(all_words.choose(rng).unwrap().clone());
    }
    Ok(selected)
}

/// Find the languages directory by checking multiple locations
fn find_languages_dir() -> Option<String> {
    let probe = "languages/english/payload_bip39.yaml";
    // Try current directory first (for development)
    if std::path::Path::new(probe).exists() {
        return Some("languages".to_string());
    }

    // Try relative to the binary location (for installed binaries)
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            // Check if languages dir is sibling to bin dir (cargo install layout)
            let languages_path = exe_dir.join("../share/glossia/languages");
            if languages_path.join("english/payload_bip39.yaml").exists() {
                return Some(languages_path.to_string_lossy().to_string());
            }

            // Check if languages dir is in the same directory as binary
            let languages_path = exe_dir.join("languages");
            if languages_path.join("english/payload_bip39.yaml").exists() {
                return Some(languages_path.to_string_lossy().to_string());
            }

            // Check if we're in a cargo install location, go up to find languages
            // ~/.cargo/bin/glossia -> ~/.cargo/share/glossia/languages
            if exe_dir.ends_with("bin") {
                let share_path = exe_dir.join("../share/glossia/languages");
                if share_path.join("english/payload_bip39.yaml").exists() {
                    return Some(share_path.to_string_lossy().to_string());
                }
            }
        }
    }

    // Try home directory cargo share location
    if let Some(home) = std::env::var_os("HOME") {
        let cargo_share = std::path::Path::new(&home).join(".cargo/share/glossia/languages");
        if cargo_share.join("english/payload_bip39.yaml").exists() {
            return Some(cargo_share.to_string_lossy().to_string());
        }
    }

    // Try CARGO_HOME if set
    if let Ok(cargo_home) = std::env::var("CARGO_HOME") {
        let cargo_share = std::path::Path::new(&cargo_home).join("share/glossia/languages");
        if cargo_share.join("english/payload_bip39.yaml").exists() {
            return Some(cargo_share.to_string_lossy().to_string());
        }
    }

    None
}

/// Exits with error if payload file doesn't exist.
/// Only used for languages without embedded files (those use embedded files instead).
/// Supports subdirectories: "math/primes" -> "languages/math/primes/payload.yaml"
pub fn get_wordlist_path(language: &str, wordlist: &str) -> Result<String, String> {
    // Languages with embedded files should not call this function
    if has_embedded_files(language) {
        return Err(format!("Language '{}' uses embedded files and should not call get_wordlist_path", language));
    }

    let (payload_filename, _) = wordlist_filenames(language, wordlist);

    // Try to find languages directory
    let languages_dir = find_languages_dir()
        .ok_or_else(|| format!("Could not find languages directory. Please ensure the 'languages' folder is accessible.\nTried: current directory, binary location, ~/.cargo/share/glossia/languages"))?;

    // Try to find payload file (supports subdirectories and recursive search)
    if let Some(payload_yaml) = find_language_file(language, &payload_filename) {
        return Ok(payload_yaml);
    }

    // Fallback: construct expected path for error message
    let expected_path = format!("{}/{}/{}", languages_dir, language, payload_filename);
    Err(format!("Wordlist file not found for language '{}'. Expected: {}\nOnly languages with a payload file are supported.",
                language, expected_path))
}

/// Find a language file (payload.yaml, cover.yaml, etc.) recursively
fn find_language_file(language: &str, filename: &str) -> Option<String> {
    let languages_dir = find_languages_dir()?;
    
    // First try exact path (supports subdirectories like "math/primes")
    let exact_path = format!("{}/{}/{}", languages_dir, language, filename);
    if std::path::Path::new(&exact_path).exists() {
        return Some(exact_path);
    }
    
    // If exact path doesn't exist, search recursively
    let languages_path = std::path::Path::new(&languages_dir);
    if let Ok(entries) = std::fs::read_dir(languages_path) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if let Some(found) = find_language_file_recursive(&path, language, filename) {
                    return Some(found);
                }
            }
        }
    }
    
    None
}

/// Recursively search for a language file matching the language name
fn find_language_file_recursive(dir: &std::path::Path, language: &str, filename: &str) -> Option<String> {
    // Check if this directory matches the language name (last component)
    if let Some(dir_name) = dir.file_name().and_then(|n| n.to_str()) {
        // If language is just the directory name (e.g., "primes" matches "primes/")
        if dir_name == language {
            let file_path = dir.join(filename);
            if file_path.exists() {
                return Some(file_path.to_string_lossy().to_string());
            }
        }

        // If language contains slashes (e.g., "math/primes"), check if path ends with it
        if language.contains('/') {
            let lang_path = std::path::Path::new(language);
            if dir.ends_with(lang_path) {
                let file_path = dir.join(filename);
                if file_path.exists() {
                    return Some(file_path.to_string_lossy().to_string());
                }
            }
        }
    }

    // Recursively search subdirectories
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if let Some(found) = find_language_file_recursive(&path, language, filename) {
                    return Some(found);
                }
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;
    use crate::types::Pos;

    #[test]
    fn test_cover_yaml_loads_refinements() {
        // Load English cover words and verify refined_cover contains expected entries
        let wordlist_set: HashSet<String> = HashSet::new();
        let (by_pos, refined_cover) = load_cover_words_by_pos(&wordlist_set, "english");

        // Verify (Det, "def") bucket exists and contains "the"
        let def_dets = refined_cover.get(&(Pos::Det, "def".to_string()));
        assert!(def_dets.is_some(), "Should have refined_cover entry for (Det, def)");
        let def_dets = def_dets.unwrap();
        assert!(def_dets.contains(&"the".to_string()), "Det[def] should contain 'the'");
        assert!(def_dets.contains(&"its".to_string()), "Det[def] should contain 'its'");
        assert!(def_dets.contains(&"our".to_string()), "Det[def] should contain 'our'");

        // Verify (Det, "indef") bucket exists and contains "a" and "an"
        let indef_dets = refined_cover.get(&(Pos::Det, "indef".to_string()));
        assert!(indef_dets.is_some(), "Should have refined_cover entry for (Det, indef)");
        let indef_dets = indef_dets.unwrap();
        assert!(indef_dets.contains(&"a".to_string()), "Det[indef] should contain 'a'");
        assert!(indef_dets.contains(&"an".to_string()), "Det[indef] should contain 'an'");

        // Verify (Cop, "sg") bucket exists and contains "is"
        let sg_cops = refined_cover.get(&(Pos::Cop, "sg".to_string()));
        assert!(sg_cops.is_some(), "Should have refined_cover entry for (Cop, sg)");
        let sg_cops = sg_cops.unwrap();
        assert!(sg_cops.contains(&"is".to_string()), "Cop[sg] should contain 'is'");

        // Verify (Cop, "pl") bucket exists and contains "are"
        let pl_cops = refined_cover.get(&(Pos::Cop, "pl".to_string()));
        assert!(pl_cops.is_some(), "Should have refined_cover entry for (Cop, pl)");
        let pl_cops = pl_cops.unwrap();
        assert!(pl_cops.contains(&"are".to_string()), "Cop[pl] should contain 'are'");

        // Verify (Det, "quant") bucket exists with quantifiers
        let quant_dets = refined_cover.get(&(Pos::Det, "quant".to_string()));
        assert!(quant_dets.is_some(), "Should have refined_cover entry for (Det, quant)");
        let quant_dets = quant_dets.unwrap();
        assert!(quant_dets.contains(&"each".to_string()), "Det[quant] should contain 'each'");
        assert!(quant_dets.contains(&"every".to_string()), "Det[quant] should contain 'every'");
        assert!(quant_dets.contains(&"some".to_string()), "Det[quant] should contain 'some'");

        // Sanity check: by_pos should also contain these words
        let all_dets = by_pos.get(&Pos::Det);
        assert!(all_dets.is_some(), "by_pos should have Det");
        let all_dets = all_dets.unwrap();
        assert!(all_dets.contains(&"the".to_string()), "by_pos[Det] should contain 'the'");
        assert!(all_dets.contains(&"a".to_string()), "by_pos[Det] should contain 'a'");
    }

    #[test]
    fn test_is_and_are_load_as_cop() {
        // Verify that "is" and "are" load as Cop (not V)
        let wordlist_set: HashSet<String> = HashSet::new();
        let (by_pos, _) = load_cover_words_by_pos(&wordlist_set, "english");

        let cop_words = by_pos.get(&Pos::Cop);
        assert!(cop_words.is_some(), "Should have Cop words");
        let cop_words = cop_words.unwrap();
        assert!(cop_words.contains(&"is".to_string()), "'is' should be in Cop");
        assert!(cop_words.contains(&"are".to_string()), "'are' should be in Cop");

        // "is" and "are" should NOT appear under V
        if let Some(v_words) = by_pos.get(&Pos::V) {
            assert!(!v_words.contains(&"is".to_string()), "'is' should NOT be in V");
            assert!(!v_words.contains(&"are".to_string()), "'are' should NOT be in V");
        }
    }

    #[test]
    fn test_words_without_refinement_not_in_refined_cover() {
        // Words without refinement tags should appear in by_pos but NOT in refined_cover
        let wordlist_set: HashSet<String> = HashSet::new();
        let (by_pos, refined_cover) = load_cover_words_by_pos(&wordlist_set, "english");

        // "bad" is Adj: 1.0 with no refinement tag
        let adj_words = by_pos.get(&Pos::Adj);
        assert!(adj_words.is_some(), "Should have Adj words");
        let adj_words = adj_words.unwrap();
        assert!(adj_words.contains(&"bad".to_string()), "'bad' should be in by_pos[Adj]");

        // "bad" should not appear in any refined_cover bucket
        let in_refined = refined_cover.iter().any(|(_, words)| {
            words.contains(&"bad".to_string())
        });
        assert!(!in_refined, "'bad' should NOT appear in refined_cover (no refinement tag)");
    }

    #[test]
    fn test_cover_words_exclude_payload_words() {
        // If a word exists in both payload and cover, it should be excluded from cover
        let mut wordlist_set: HashSet<String> = HashSet::new();
        // "aid" is in English cover.yaml as N/V. Let's add it to the wordlist set.
        wordlist_set.insert("aid".to_string());

        let (by_pos, _) = load_cover_words_by_pos(&wordlist_set, "english");

        // "aid" should be excluded from the cover words
        for (_, words) in &by_pos {
            assert!(!words.contains(&"aid".to_string()),
                "'aid' should be excluded from cover words when it is in the wordlist set");
        }
    }

    #[test]
    fn test_load_payload_words_english() {
        // Verify we can load English payload words and they contain some known BIP39 words
        let words = load_payload_words("english").expect("Should load English payload words");
        assert!(!words.is_empty(), "English payload words should not be empty");
        // BIP39 word list includes "abandon" as first word
        assert!(words.contains(&"abandon".to_string()), "Should contain 'abandon'");
        // Words should be sorted
        let mut sorted = words.clone();
        sorted.sort();
        assert_eq!(words, sorted, "Payload words should be sorted");
    }

    #[test]
    fn test_build_pos_mapping_english() {
        // Verify that building POS mapping for English produces valid entries
        let mapping = build_pos_mapping("english").expect("Should build English POS mapping");
        assert!(!mapping.is_empty(), "POS mapping should not be empty");

        // "abandon" should have POS tags
        let abandon_pos = mapping.get("abandon");
        assert!(abandon_pos.is_some(), "'abandon' should have POS tags");
        let abandon_pos = abandon_pos.unwrap();
        assert!(!abandon_pos.is_empty(), "'abandon' should have at least one POS tag");
    }

    #[test]
    fn test_parse_pos_tag_default_all_variants() {
        // Verify all standard POS tag strings parse correctly
        assert_eq!(parse_pos_tag_default("Det"), Some(Pos::Det));
        assert_eq!(parse_pos_tag_default("Adj"), Some(Pos::Adj));
        assert_eq!(parse_pos_tag_default("N"), Some(Pos::N));
        assert_eq!(parse_pos_tag_default("V"), Some(Pos::V));
        assert_eq!(parse_pos_tag_default("Modal"), Some(Pos::Modal));
        assert_eq!(parse_pos_tag_default("Aux"), Some(Pos::Aux));
        assert_eq!(parse_pos_tag_default("Cop"), Some(Pos::Cop));
        assert_eq!(parse_pos_tag_default("To"), Some(Pos::To));
        assert_eq!(parse_pos_tag_default("Prep"), Some(Pos::Prep));
        assert_eq!(parse_pos_tag_default("Adv"), Some(Pos::Adv));
        assert_eq!(parse_pos_tag_default("Conj"), Some(Pos::Conj));
        assert_eq!(parse_pos_tag_default("Dot"), Some(Pos::Dot));
        assert_eq!(parse_pos_tag_default("Prefix"), Some(Pos::Prefix));
        assert_eq!(parse_pos_tag_default("Unknown"), None);
    }
}
